name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.11'
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8
         pip install pandas
         pip install pytest
         pip install pytest-subtests
      - name: Run tests
        run: |
          python -m unittest discover -s tests
      - name: Lint with flake8
        run: |
          # stop the build if the are Python syntax errors or undefined names
          flake8 .
